$(document).ready(function(){document.fonts.ready.then(()=>{document.body.style.visibility="visible"});adClas=$('.more-comments .user-comment[class="user-comment"]').addClass("desi");let sizeItems=$(".more-comments .user-comment").length,comentItem=0;$(".more-comments .desi:lt("+comentItem+")").fadeIn();$(".more-comments-btn").click(function(){comentItem=comentItem+20<=sizeItems?comentItem+20:sizeItems;$(".more-comments .desi:lt("+comentItem+")").addClass("comShow");let answer=$(".more-comments").find(".admin-response");if(answer.prev().hasClass("comShow")){$(".comShow").next(".admin-response").fadeIn().addClass("comShow")}
$(".more-comments .desi:lt("+comentItem+")").fadeIn();let fulsize=$(".more-comments .comShow").length;if(fulsize==sizeItems){$(".more-comments-btn").hide()}});$(".select-bank-box").on("click",function(){$(".select-bank-box").css("border-color","#dcdcdc");$(this).css("border-color","#007bff")});$(".emoji").on("click",function(){$(".emoji").removeClass("active");$(this).addClass("active")});$(".faq .faq-box h3").on("click",function(){if($(this).hasClass("active")){$(this).next().slideUp(300);$(this).removeClass("active");$(this).parent().removeClass("active")}else{$(".faq-answer-box").slideUp(300);$(".faq-box h3").removeClass("active");$(".faq-box").removeClass("active");$(this).next().slideDown(300);$(this).addClass("active");$(this).parent().addClass("active")}});$(".select-bank-box").click(function(){if($(this).find("input:radio[name=bankname]").is(":checked")){$(this).find("input:radio[name=bankname]").attr("checked",!1)}else{$(this).find("input:radio[name=bankname]").prop("checked",!0)}});$("input[type=radio]").click(function(e){e.stopPropagation()});$(".emoji").click(function(){if($(this).find("input:radio[name=emoji]").is(":checked")){$(this).find("input:radio[name=emoji]").attr("checked",!1)}else{$(this).find("input:radio[name=emoji]").prop("checked",!0)}});$(".license-box").on("click",function(){var src=$(this).find("img").attr("src");$("#license-page-modal").css("display","block");$("#license-page-modal").find("img").attr("src",src)});$(".count").each(function(){$(this).prop("Counter",0).animate({Counter:$(this).text()},{duration:10000,easing:"swing",step:function(now){$(this).text(Math.ceil(now).toLocaleString())},})})});function disableSubmit(){var submitBtn=document.getElementById("submit-btn");if(submitBtn.disabled){submitBtn.disabled=!1;submitBtn.style.cursor="pointer"}else{submitBtn.disabled=!0;submitBtn.style.cursor="not-allowed";alert("Ø§Ù…Ú©Ø§Ù† Ø®Ø±ÛŒØ¯ Ø§Ø² Ø³Ø§ÛŒØª Ù‚Ù… ØªÛŒÚ©ØªØŒ Ù…Ø³ØªÙ„Ø²Ù… Ù¾Ø°ÛŒØ±Ø´ Ù‚ÙˆØ§Ù†ÛŒÙ† Ù…ÛŒØ¨Ø§Ø´Ø¯.")}}
var myCollapsibleNavbar=document.getElementById("collapsibleNavbar");var collapseBtn=document.getElementById("my-collapse-btn");var mjModalForCollapse=document.getElementById("mj-modal-for-collapse");window.onclick=function(event){if(event.target==mjModalForCollapse){myCollapsibleNavbar.style.right="-250px";mjModalForCollapse.style.display="none"}};function mjOpenSidebar(){var myCollapsibleNavbar=document.getElementById("collapsibleNavbar");var mjModalForCollapse=document.getElementById("mj-modal-for-collapse");myCollapsibleNavbar.style.right="0";mjModalForCollapse.style.display="block"}(function(factory){if(typeof define==="function"&&define.amd){define(["jquery"],factory)}else if(typeof exports==="object"){module.exports=factory(require("jquery"))}else{factory(jQuery)}})(function($){var pluses=/\+/g;function encode(s){return config.raw?s:encodeURIComponent(s)}
function decode(s){return config.raw?s:decodeURIComponent(s)}
function stringifyCookieValue(value){return encode(config.json?JSON.stringify(value):String(value))}
function parseCookieValue(s){if(s.indexOf('"')===0){s=s.slice(1,-1).replace(/\\"/g,'"').replace(/\\\\/g,"\\")}
try{s=decodeURIComponent(s.replace(pluses," "));return config.json?JSON.parse(s):s}catch(e){}}
function read(s,converter){var value=config.raw?s:parseCookieValue(s);return $.isFunction(converter)?converter(value):value}
var config=($.cookie=function(key,value,options){if(arguments.length>1&&!$.isFunction(value)){options=$.extend({},config.defaults,options);if(typeof options.expires==="number"){var days=options.expires,t=(options.expires=new Date());t.setMilliseconds(t.getMilliseconds()+days*864e5)}
return(document.cookie=[encode(key),"=",stringifyCookieValue(value),options.expires?"; expires="+options.expires.toUTCString():"",options.path?"; path="+options.path:"",options.domain?"; domain="+options.domain:"",options.secure?"; secure":"",].join(""))}
var result=key?undefined:{},cookies=document.cookie?document.cookie.split("; "):[],i=0,l=cookies.length;for(;i<l;i++){var parts=cookies[i].split("="),name=decode(parts.shift()),cookie=parts.join("=");if(key===name){result=read(cookie,value);break}
if(!key&&(cookie=read(cookie))!==undefined){result[name]=cookie}}
return result});config.defaults={};$.removeCookie=function(key,options){$.cookie(key,"",$.extend({},options,{expires:-1}));return!$.cookie(key)}});if(!$.cookie("datafavorites")){var favorite=[]}else{var retrievedData=$.cookie("datafavorites");var favorite=JSON.parse(retrievedData);favorite.forEach(myFunction);function myFunction(value,index,array){$(".favorite-box[data-id='"+value+"']").addClass("active")}}
$(".favorite-box").click(function(){favval=$(this).closest(".favorite-box").data("id");if($(this).closest(".favorite-box").is(".active")){favorite=jQuery.grep(favorite,function(value){return value!=favval});$.cookie("datafavorites",JSON.stringify(favorite),{expires:365,path:"/"});$(this).closest(".favorite-box").removeClass("active");$(".mis_fav_alert").removeClass("show");setTimeout(function(){$(".mis_fav_alert").addClass("show")},0)}else{favorite.push(favval);$.cookie("datafavorites",JSON.stringify(favorite),{expires:365,path:"/"});$(this).closest(".favorite-box").addClass("active");$(".fav_alert").removeClass("show");setTimeout(function(){$(".fav_alert").addClass("show")},0)}});$(".fav_alert .close_btn, .mis_fav_alert .close_btn").click(function(e){e.preventDefault();$(".mis_fav_alert").removeClass("show");$(".fav_alert").removeClass("show")})
